spring:
  application:
      name:
        store
  datasource:
        url:
          ${DB_URL}
        username:
          ${DB_USER}
        password:
          ${DB_PASSWORD}
        driver-class-name: org.mariadb.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
server:
  port:
    ${PORT}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}